Build script passes ShellCheck

diff --git a/build-llvm-byfl b/build-llvm-byfl
--- a/build-llvm-byfl
+++ b/build-llvm-byfl
@@ -10,20 +10,20 @@
 
 # Ensure we have a version of bash that can parse the rest of this
 # file (specifically, the coproc statement).
-if [ `echo $BASH_VERSION | sed -e 's/\..*//'` -lt 4 ] ; then
+if [ "${BASH_VERSION/.*/}" -lt 4 ] ; then
     echo "${0}: This script requires bash version 4+; you're running version $BASH_VERSION" 1>&2;
     exit 1
 fi
 
 # Define a function to work around OS X's lack of "readlink -f".
 function abs_dirname() {
-  somedir=`echo "$1/" | sed 's,//*,/,g'`
-  if [ `echo "$somedir" | cut -c1` = "/" ] ; then
-      echo "$somedir"
-  else
-      mkdir -p "$somedir" > /dev/null 2>&1
-      (cd "${somedir%/*}" && pwd -P)
-  fi
+    somedir=$(echo "$1/" | sed 's,//*,/,g')
+    if [ "${somedir:0:1}" = "/" ] ; then
+	echo "$somedir"
+    else
+	mkdir -p "$somedir" > /dev/null 2>&1
+	(cd "${somedir%/*}" && pwd -P)
+    fi
 }
 
 # Determine where to build, where to install, and how many processes to use.
@@ -83,6 +83,16 @@ while getopts j:b:r:tdcCD:x:B:L: opt; do
             # Exclude a feature from download/compiling.
             export "use_${OPTARG}"=no
             ;;
+
+	B)
+	    # Specify a specific branch of Byfl to use.
+	    byfl_branch="$OPTARG"
+	    ;;
+
+	L)
+	    # Specify a specific branch of LLVM/Clang to use.
+	    llvm_branch="$OPTARG"
+	    ;;
     esac
 done
 shift $((OPTIND-1))
@@ -91,15 +101,15 @@ if [ -z "$1" ] ; then
     exit 1
 fi
 if [ -z "$builddir" ] ; then
-    builddir=$(mktemp --directory --tmpdir=$(/bin/pwd) byfl-build.XXXXXX)
+    builddir=$(mktemp --directory --tmpdir="$(/bin/pwd)" byfl-build.XXXXXX)
 fi
-builddir=`abs_dirname "$builddir"`
-installdir=`abs_dirname "$1"`
+builddir=$(abs_dirname "$builddir")
+installdir=$(abs_dirname "$1")
 if [ -z "$numprocs" ] ; then
     # No parallel-build factor was specified -- guess a good value to use.
     if [ -e /proc/cpuinfo ] ; then
         # Linux -- get the CPU count from /proc/cpuinfo.
-        numprocs=`cat /proc/cpuinfo | egrep -c '^processor'`
+        numprocs=$(egrep -c '^processor' /proc/cpuinfo)
     else
         # OS X or other -- disable implicit parallel builds.
         numprocs=1
@@ -112,30 +122,31 @@ CXX=${CXX:-g++}
 
 # Prepare the GUI.
 if [ "$gui" = yes ] ; then
-    if [ ! `type -P stdbuf` ] ; then
+    if [ ! "$(type -P stdbuf)" ] ; then
         gui=no
-    elif [ ! `type -P zenity` ] ; then
+    elif [ ! "$(type -P zenity)" ] ; then
         gui=no
     fi
 fi
 if [ "$gui" = yes ] ; then
+    zproc_PID=""   # Prevent spurious undefined-variable warnings from ShellCheck.
     coproc zproc {
         zenity --progress --title="Byfl installation progress" --auto-kill
     }
     while [ -z "$zenity_pid" ] ; do
-        zenity_pid=`ps | awk '$NF == "zenity" {print $1}'`
+        zenity_pid=$(ps | awk '$NF == "zenity" {print $1}')
         sleep 1
     done
     function abend () {
-        test -z "$zproc_PID" || kill $zproc_PID
+        test -z "$zproc_PID" || kill "$zproc_PID"
         zenity --error --title="Fail" --text="Installation failed."
         exit 1
     }
     trap abend ERR
 else
-    zproc=(0, 1)
+    zproc=(0 1)
 fi
-exec 4>&${zproc[1]}
+exec 4>&"${zproc[1]}"
 
 # Define a function to update a progress bar during command execution
 # given a symbolic tag for the run, the expected number of lines of
@@ -149,20 +160,20 @@ function run_with_progress () {
 
     # Run the command either with or without the GUI.  Abort on error.
     logfile="$builddir/build-logs/$tag.log"
-    echo "\$ $@" > $logfile
+    echo "\$ $*" > "$logfile"
     if [ "$gui" = yes ] ; then
         # Estimate the number of lines of output we'll see.
         echo 0 1>&4
         "$@" 2>&1 | \
-            tee -a $logfile | \
-            stdbuf -oL awk '{printf "%d\n", 100*NR/MAXLN; print > "/dev/stderr"}' MAXLN=$maxlines | \
+            tee -a "$logfile" | \
+            stdbuf -oL awk '{printf "%d\n", 100*NR/MAXLN; print > "/dev/stderr"}' MAXLN="$maxlines" | \
             stdbuf -oL uniq 1>&4
-        echo 100 1>&4
+            echo 100 1>&4
     else
         "$@"
     fi
     if [ "${PIPESTATUS[0]}" != 0 ] ; then
-        echo "${0}: Execution of \"$@\" failed (${PIPESTATUS[0]})" 1>&2
+        echo "${0}: Execution of \"$*\" failed (${PIPESTATUS[0]})" 1>&2
         false
         exit 1
     fi
@@ -185,38 +196,38 @@ if [ "$download" = yes ] ; then
     # Delete old files before downloading the new ones.
     if [ "$use_byfl" = yes ] ; then
         echo "# Removing old versions of Byfl from $builddir" 1>&4
-        run_with_progress cleanup-byfl 310 rm -rfv byfl
+        run_with_progress cleanup-byfl 320 rm -rfv byfl
     fi
     if [ "$use_llvm" = yes ] ; then
         echo "# Removing old versions of LLVM and Clang from $builddir" 1>&4
-        run_with_progress cleanup-llvm 67000 rm -rfv llvm
+        run_with_progress cleanup-llvm 69000 rm -rfv llvm
     fi
 
     # Download LLVM trunk.
     if [ "$use_llvm" = yes ] ; then
-        echo "# Downloading LLVM into $builddir" 1>&4
-        run_with_progress llvm-dl 18000 svn checkout -r $llvm_revision http://llvm.org/svn/llvm-project/llvm/trunk llvm
+        echo "# Downloading LLVM revision $llvm_revision on $llvm_branch into $builddir" 1>&4
+        run_with_progress llvm-dl 19000 svn checkout -r "$llvm_revision" "http://llvm.org/svn/llvm-project/llvm/$llvm_branch" llvm
     fi
-    cd llvm
-    llvm_revision=`svn info | awk '/^Revision: / {print $2}'`
-    cd ..
+    pushd llvm
+    llvm_revision=$(svn info | awk '/^Revision: / {print $2}')
+    popd
 
     # Download Clang.
     if [ "$use_llvm" = yes ] ; then
         echo "# Downloading Clang revision $llvm_revision into $builddir" 1>&4
-        run_with_progress clang-dl 13000 svn checkout -r $llvm_revision http://llvm.org/svn/llvm-project/cfe/trunk llvm/tools/clang
+        run_with_progress clang-dl 14000 svn checkout -r "$llvm_revision" "http://llvm.org/svn/llvm-project/cfe/$llvm_branch" llvm/tools/clang
     fi
 
     # Download the Clang run-time system.
     if [ "$use_llvm" = yes ] ; then
         echo "# Downloading Clang RT revision $llvm_revision into $builddir" 1>&4
-        run_with_progress rts-dl 1900 svn checkout -r $llvm_revision http://llvm.org/svn/llvm-project/compiler-rt/$llvm_branch llvm/projects/compiler-rt
+        run_with_progress rts-dl 2000 svn checkout -r "$llvm_revision" "http://llvm.org/svn/llvm-project/compiler-rt/$llvm_branch" llvm/projects/compiler-rt
     fi
 
     # Download Byfl.
     if [ "$use_byfl" = yes ] ; then
-        echo "# Downloading Byfl into $builddir" 1>&4
-        run_with_progress byfl-dl 2 git clone https://github.com/losalamos/Byfl.git byfl
+        echo "# Downloading Byfl branch $byfl_branch into $builddir" 1>&4
+        run_with_progress byfl-dl 2 git clone --branch="$byfl_branch" https://github.com/losalamos/Byfl.git byfl
     fi
 
     # Say what we did.
@@ -226,7 +237,7 @@ if [ "$download" = yes ] ; then
         echo "Downloaded a subset of LLVM, Clang, and Byfl into $builddir."
     fi
     if [ "$gui" = yes -a "$compile" = no ] ; then
-        kill $zenity_pid
+        kill "$zenity_pid"
         zenity --info --title="Finished downloading" --text="Downloaded LLVM, Clang,\nand Byfl into $builddir."
     fi
 fi
@@ -236,19 +247,22 @@ if [ "$compile" = yes ] ; then
     if [ "$use_llvm" = yes ] ; then
         # Configure LLVM and Clang.
         echo "# Configuring LLVM and Clang" 1>&4
-        cd llvm
+        pushd llvm
         if [ $configure = yes -o ! -e config.log ] ; then
             run_with_progress llvm-config 250 ./configure --prefix="$installdir" --enable-optimized --enable-debug-runtime --enable-debug-symbols --disable-assertions CC="$CC" CXX="$CXX" REQUIRES_RTTI=1
         fi
 
         # Build LLVM and Clang.
         echo "# Compiling LLVM and Clang" 1>&4
-        run_with_progress llvm-build 3200 make -j$numprocs
+        run_with_progress llvm-build 3500 make -j$numprocs
 
-        # Install LLVM and Clang.
+        # Install LLVM and Clang.  Out of the goodness of our heart we also
+        # install the Clang static analyzer.
         echo "# Installing LLVM and Clang into $destdir$installdir" 1>&4
-        run_with_progress llvm-inst 840 make DESTDIR="$destdir" install
-        cd ..
+        run_with_progress llvm-inst 860 make DESTDIR="$destdir" install
+	cp -p tools/clang/tools/scan-view/scan-view "$destdir$installdir/bin/scan-view"
+	cp -p tools/clang/tools/scan-build/scan-build "$destdir$installdir/bin/scan-build"
+        popd
     fi
     export PATH="$destdir$installdir/bin:$PATH"
 
@@ -257,17 +271,17 @@ if [ "$compile" = yes ] ; then
         echo "# Configuring Byfl" 1>&4
         cd byfl
         if [ $configure = yes -o ! -e config.log ] ; then
-            run_with_progress byfl-autogen 21 autoreconf -v -f -i
+            run_with_progress byfl-autogen 22 autoreconf -v -f -i
         fi
         test -e build || mkdir build
         cd build
         if [ $configure = yes -o ! -e config.log ] ; then
-            run_with_progress byfl-config 140 ../configure --prefix="$installdir"
+            run_with_progress byfl-config 150 ../configure --prefix="$installdir"
         fi
 
         # Build Byfl.
         echo "# Compiling Byfl" 1>&4
-        run_with_progress byfl-build 200 make -j$numprocs
+        run_with_progress byfl-build 210 make -j$numprocs
 
         # Install Byfl.
         echo "# Installing Byfl into $destdir$installdir" 1>&4
@@ -277,8 +291,8 @@ if [ "$compile" = yes ] ; then
     # Test the installation
     echo "# Testing the Byfl installation" 1>&4
     test "$gui" = yes && echo 0 1>&4
-    cfile=`mktemp --tmpdir --suffix=.c byfltest-XXXXXX`
-    exefile=`echo $cfile | sed 's/\.c$//'`
+    cfile=$(mktemp --tmpdir --suffix=.c byfltest-XXXXXX)
+    exefile=${cfile%.c}
     cat <<CFILE > $cfile
 #include <stdio.h>
 int main (void) {
@@ -286,15 +300,15 @@ int main (void) {
   return 0;
 }
 CFILE
-    bf-clang -O2 -bf-libdir="$destdir$installdir/lib" $cfile -o $exefile
-    run_with_progress byfl-test 19 $exefile
-    rm -f $cfile $exefile
+    bf-clang -O2 -bf-libdir="$destdir$installdir/lib" "$cfile" -o "$exefile"
+    run_with_progress byfl-test 20 "$exefile"
+    rm -f "$cfile" "$exefile"
 
     # Say what we did.
     echo "Successfully installed LLVM, Clang, and Byfl into $installdir."
     echo "It is now safe to delete $builddir."
     if [ "$gui" = yes ] ; then
-        kill $zenity_pid
+        kill "$zenity_pid"
         zenity --info --title="Finished installation" --text="Successfully installed LLVM, Clang, and Byfl into $installdir.\n\nIt is now safe to delete $builddir."
     fi
 fi
