Build script passes ShellCheck

diff --git a/build-llvm-byfl b/build-llvm-byfl
--- a/build-llvm-byfl
+++ b/build-llvm-byfl
@@ -1,29 +1,29 @@
 #! /bin/bash
 
-######################################
-# Automatically do a clean build of  #
-# LLVM 3.5 and Clang 3.5 and then of #
-# Byfl's llvm-3.5 branch             #
-#                                    #
-# By Scott Pakin <pakin@lanl.gov>    #
-######################################
+##########################################
+# Automatically do a clean build of      #
+# LLVM 3.5, Clang 3.5, and DragonEgg 3.5 #
+# and then of Byfl's llvm-3.5 branch     #
+#                                        #
+# By Scott Pakin <pakin@lanl.gov>        #
+##########################################
 
 # Ensure we have a version of bash that can parse the rest of this
 # file (specifically, the coproc statement).
-if [ `echo $BASH_VERSION | sed -e 's/\..*//'` -lt 4 ] ; then
+if [ "${BASH_VERSION/.*/}" -lt 4 ] ; then
     echo "${0}: This script requires bash version 4+; you're running version $BASH_VERSION" 1>&2;
     exit 1
 fi
 
 # Define a function to work around OS X's lack of "readlink -f".
 function abs_dirname() {
-  somedir=`echo "$1/" | sed 's,//*,/,g'`
-  if [ `echo "$somedir" | cut -c1` = "/" ] ; then
-      echo "$somedir"
-  else
-      mkdir -p "$somedir" > /dev/null 2>&1
-      (cd "${somedir%/*}" && pwd -P)
-  fi
+    somedir=$(echo "$1/" | sed 's,//*,/,g')
+    if [ "${somedir:0:1}" = "/" ] ; then
+        echo "$somedir"
+    else
+        mkdir -p "$somedir" > /dev/null 2>&1
+        (cd "${somedir%/*}" && pwd -P)
+    fi
 }
 
 # Determine where to build, where to install, and how many processes to use.
@@ -85,15 +85,15 @@ while getopts j:b:r:tdcCD:x:B:L: opt; do
             export "use_${OPTARG}"=no
             ;;
 
-	B)
-	    # Specify a specific branch of Byfl to use.
-	    byfl_branch="$OPTARG"
-	    ;;
+        B)
+            # Specify a specific branch of Byfl to use.
+            byfl_branch="$OPTARG"
+            ;;
 
-	L)
-	    # Specify a specific branch of LLVM/Clang/DragonEgg to use.
-	    llvm_branch="$OPTARG"
-	    ;;
+        L)
+            # Specify a specific branch of LLVM/Clang/DragonEgg to use.
+            llvm_branch="$OPTARG"
+            ;;
     esac
 done
 shift $((OPTIND-1))
@@ -102,15 +102,15 @@ if [ -z "$1" ] ; then
     exit 1
 fi
 if [ -z "$builddir" ] ; then
-    builddir=$(mktemp --directory --tmpdir=$(/bin/pwd) byfl-build.XXXXXX)
+    builddir=$(mktemp --directory --tmpdir="$(/bin/pwd)" byfl-build.XXXXXX)
 fi
-builddir=`abs_dirname "$builddir"`
-installdir=`abs_dirname "$1"`
+builddir=$(abs_dirname "$builddir")
+installdir=$(abs_dirname "$1")
 if [ -z "$numprocs" ] ; then
     # No parallel-build factor was specified -- guess a good value to use.
     if [ -e /proc/cpuinfo ] ; then
         # Linux -- get the CPU count from /proc/cpuinfo.
-        numprocs=`cat /proc/cpuinfo | egrep -c '^processor'`
+        numprocs=$(egrep -c '^processor' /proc/cpuinfo)
     else
         # OS X or other -- disable implicit parallel builds.
         numprocs=1
@@ -123,45 +123,46 @@ CXX=${CXX:-g++}
 
 # Ensure we have a version of GCC that works with DragonEgg.
 if [ "$use_dragonegg" = yes ] ; then
-    gcc_version=`$CC --version | awk 'NR==1 {sub(/\([^\)]*\)/, ""); print $2}'`
-    if `echo $gcc_version | awk '!/^4\.[5-8]\./ {exit 1}'` ; then
+    gcc_version=$($CC --version | awk 'NR==1 {sub(/\([^\)]*\)/, ""); print $2}')
+    if echo "$gcc_version" | awk '!/^4\.[5-8]\./ {exit 1}' ; then
         :
     else
         echo "${0}: DragonEgg requires GCC version 4.5, 4.6, 4.7, or 4.8; version $gcc_version almost certainly won't work" 1>&2
         exit 1
     fi
-    if [ `$CC -print-file-name=plugin` = plugin ] ; then
-        echo "${0}: DragonEgg requires the GCC plugin development files (e.g., auto-host.h) corresponding to `$CC --version | head -1`" 1>&2
+    if [ "$($CC -print-file-name=plugin)" = plugin ] ; then
+        echo "${0}: DragonEgg requires the GCC plugin development files (e.g., auto-host.h) corresponding to $($CC --version | head -1)" 1>&2
         exit 1
     fi
 fi
 
 # Prepare the GUI.
 if [ "$gui" = yes ] ; then
-    if [ ! `type -P stdbuf` ] ; then
+    if [ ! "$(type -P stdbuf)" ] ; then
         gui=no
-    elif [ ! `type -P zenity` ] ; then
+    elif [ ! "$(type -P zenity)" ] ; then
         gui=no
     fi
 fi
 if [ "$gui" = yes ] ; then
+    zproc_PID=""   # Prevent spurious undefined-variable warnings from ShellCheck.
     coproc zproc {
         zenity --progress --title="Byfl installation progress" --auto-kill
     }
     while [ -z "$zenity_pid" ] ; do
-        zenity_pid=`ps | awk '$NF == "zenity" {print $1}'`
+        zenity_pid=$(ps | awk '$NF == "zenity" {print $1}')
         sleep 1
     done
     function abend () {
-        test -z "$zproc_PID" || kill $zproc_PID
+        test -z "$zproc_PID" || kill "$zproc_PID"
         zenity --error --title="Fail" --text="Installation failed."
         exit 1
     }
     trap abend ERR
 else
-    zproc=(0, 1)
+    zproc=(0 1)
 fi
-exec 4>&${zproc[1]}
+exec 4>&"${zproc[1]}"
 
 # Define a function to update a progress bar during command execution
 # given a symbolic tag for the run, the expected number of lines of
@@ -175,20 +176,20 @@ function run_with_progress () {
 
     # Run the command either with or without the GUI.  Abort on error.
     logfile="$builddir/build-logs/$tag.log"
-    echo "\$ $@" > $logfile
+    echo "\$ $*" > "$logfile"
     if [ "$gui" = yes ] ; then
         # Estimate the number of lines of output we'll see.
         echo 0 1>&4
         "$@" 2>&1 | \
-            tee -a $logfile | \
-            stdbuf -oL awk '{printf "%d\n", 100*NR/MAXLN; print > "/dev/stderr"}' MAXLN=$maxlines | \
+            tee -a "$logfile" | \
+            stdbuf -oL awk '{printf "%d\n", 100*NR/MAXLN; print > "/dev/stderr"}' MAXLN="$maxlines" | \
             stdbuf -oL uniq 1>&4
-        echo 100 1>&4
+            echo 100 1>&4
     else
         "$@"
     fi
     if [ "${PIPESTATUS[0]}" != 0 ] ; then
-        echo "${0}: Execution of \"$@\" failed (${PIPESTATUS[0]})" 1>&2
+        echo "${0}: Execution of \"$*\" failed (${PIPESTATUS[0]})" 1>&2
         false
         exit 1
     fi
@@ -211,42 +212,42 @@ if [ "$download" = yes ] ; then
     # Delete old files before downloading the new ones.
     if [ "$use_byfl" = yes ] ; then
         echo "# Removing old versions of Byfl from $builddir" 1>&4
-        run_with_progress cleanup-byfl 310 rm -rfv byfl
+        run_with_progress cleanup-byfl 320 rm -rfv byfl
     fi
     if [ "$use_dragonegg" = yes ] ; then
         echo "# Removing old versions of DragonEgg from $builddir" 1>&4
-        run_with_progress cleanup-dregg 980 rm -rfv dragonegg
+        run_with_progress cleanup-dregg 970 rm -rfv dragonegg
     fi
     if [ "$use_llvm" = yes ] ; then
         echo "# Removing old versions of LLVM and Clang from $builddir" 1>&4
-        run_with_progress cleanup-llvm 60000 rm -rfv llvm
+        run_with_progress cleanup-llvm 62000 rm -rfv llvm
     fi
 
     # Download LLVM.
     if [ "$use_llvm" = yes ] ; then
         echo "# Downloading LLVM revision $llvm_revision on $llvm_branch into $builddir" 1>&4
-        run_with_progress llvm-dl 16000 svn checkout -r $llvm_revision http://llvm.org/svn/llvm-project/llvm/$llvm_branch llvm
+        run_with_progress llvm-dl 16000 svn checkout -r "$llvm_revision" "http://llvm.org/svn/llvm-project/llvm/$llvm_branch" llvm
     fi
-    cd llvm
-    llvm_revision=`svn info | awk '/^Revision: / {print $2}'`
-    cd ..
+    pushd llvm
+    llvm_revision=$(svn info | awk '/^Revision: / {print $2}')
+    popd
 
     # Download Clang.
     if [ "$use_llvm" = yes ] ; then
         echo "# Downloading Clang revision $llvm_revision into $builddir" 1>&4
-        run_with_progress clang-dl 12000 svn checkout -r $llvm_revision http://llvm.org/svn/llvm-project/cfe/$llvm_branch llvm/tools/clang
+        run_with_progress clang-dl 13000 svn checkout -r "$llvm_revision" "http://llvm.org/svn/llvm-project/cfe/$llvm_branch" llvm/tools/clang
     fi
 
     # Download the Clang run-time system.
     if [ "$use_llvm" = yes ] ; then
         echo "# Downloading Clang RT revision $llvm_revision into $builddir" 1>&4
-        run_with_progress rts-dl 1800 svn checkout -r $llvm_revision http://llvm.org/svn/llvm-project/compiler-rt/$llvm_branch llvm/projects/compiler-rt
+        run_with_progress rts-dl 1800 svn checkout -r "$llvm_revision" "http://llvm.org/svn/llvm-project/compiler-rt/$llvm_branch" llvm/projects/compiler-rt
     fi
 
     # Download DragonEgg.
     if [ "$use_dragonegg" = yes ] ; then
         echo "# Downloading DragonEgg revision $llvm_revision into $builddir" 1>&4
-        run_with_progress dregg-dl 400 svn checkout -r $llvm_revision http://llvm.org/svn/llvm-project/dragonegg/$llvm_branch dragonegg
+        run_with_progress dregg-dl 410 svn checkout -r "$llvm_revision" "http://llvm.org/svn/llvm-project/dragonegg/$llvm_branch" dragonegg
     fi
 
     # Download Byfl.
@@ -262,7 +263,7 @@ if [ "$download" = yes ] ; then
         echo "Downloaded a subset of LLVM, Clang, DragonEgg, and Byfl into $builddir."
     fi
     if [ "$gui" = yes -a "$compile" = no ] ; then
-        kill $zenity_pid
+        kill "$zenity_pid"
         zenity --info --title="Finished downloading" --text="Downloaded LLVM, Clang, DragonEgg,\nand Byfl into $builddir."
     fi
 fi
@@ -272,35 +273,35 @@ if [ "$compile" = yes ] ; then
     if [ "$use_llvm" = yes ] ; then
         # Configure LLVM and Clang.
         echo "# Configuring LLVM and Clang" 1>&4
-        cd llvm
+        pushd llvm
         if [ $configure = yes -o ! -e config.log ] ; then
-            run_with_progress llvm-config 270 ./configure --prefix="$installdir" --enable-optimized --enable-debug-runtime --enable-debug-symbols --disable-assertions CC="$CC" CXX="$CXX" REQUIRES_RTTI=1
+            run_with_progress llvm-config 280 ./configure --prefix="$installdir" --enable-optimized --enable-debug-runtime --enable-debug-symbols --disable-assertions CC="$CC" CXX="$CXX" REQUIRES_RTTI=1
         fi
 
         # Build LLVM and Clang.
         echo "# Compiling LLVM and Clang" 1>&4
-        run_with_progress llvm-build 3700 make -j$numprocs
+        run_with_progress llvm-build 4100 make -j$numprocs
 
         # Install LLVM and Clang.  Out of the goodness of our heart we also
         # install the Clang static analyzer.
         echo "# Installing LLVM and Clang into $destdir$installdir" 1>&4
-        run_with_progress llvm-inst 820 make DESTDIR="$destdir" install
-	cp -p tools/clang/tools/scan-view/scan-view "$destdir$installdir/bin/scan-view"
-	cp -p tools/clang/tools/scan-build/scan-build "$destdir$installdir/bin/scan-build"
-        cd ..
+        run_with_progress llvm-inst 850 make DESTDIR="$destdir" install
+        cp -p tools/clang/tools/scan-view/scan-view "$destdir$installdir/bin/scan-view"
+        cp -p tools/clang/tools/scan-build/scan-build "$destdir$installdir/bin/scan-build"
+        popd
     fi
     export PATH="$destdir$installdir/bin:$PATH"
 
     if [ "$use_dragonegg" = yes ] ; then
         # Build DragonEgg.
-        cd dragonegg
+        pushd dragonegg
         echo "# Compiling DragonEgg" 1>&4
-        run_with_progress dregg-build 310 make -j$numprocs
+        run_with_progress dregg-build 320 make -j$numprocs
 
         # Install DragonEgg.
         echo "# Installing DragonEgg into $destdir$installdir" 1>&4
         run_with_progress dregg-inst 2 cp -v dragonegg.so "$destdir$installdir/lib/"
-        cd ..
+        popd
     fi
 
     if [ "$use_byfl" = yes ] ; then
@@ -308,17 +309,17 @@ if [ "$compile" = yes ] ; then
         echo "# Configuring Byfl" 1>&4
         cd byfl
         if [ $configure = yes -o ! -e config.log ] ; then
-            run_with_progress byfl-autogen 21 autoreconf -v -f -i
+            run_with_progress byfl-autogen 22 autoreconf -v -f -i
         fi
         test -e build || mkdir build
         cd build
         if [ $configure = yes -o ! -e config.log ] ; then
-            run_with_progress byfl-config 140 ../configure DRAGONEGG="$installdir/lib/dragonegg.so" --prefix="$installdir"
+            run_with_progress byfl-config 150 ../configure DRAGONEGG="$installdir/lib/dragonegg.so" --prefix="$installdir"
         fi
 
         # Build Byfl.
         echo "# Compiling Byfl" 1>&4
-        run_with_progress byfl-build 190 make DRAGONEGG="$destdir$installdir/lib/dragonegg.so" -j$numprocs
+        run_with_progress byfl-build 200 make DRAGONEGG="$destdir$installdir/lib/dragonegg.so" -j$numprocs
 
         # Install Byfl.
         echo "# Installing Byfl into $destdir$installdir" 1>&4
@@ -328,8 +329,8 @@ if [ "$compile" = yes ] ; then
     # Test the installation
     echo "# Testing the Byfl installation" 1>&4
     test "$gui" = yes && echo 0 1>&4
-    cfile=`mktemp --tmpdir --suffix=.c byfltest-XXXXXX`
-    exefile=`echo $cfile | sed 's/\.c$//'`
+    cfile=$(mktemp --tmpdir --suffix=.c byfltest-XXXXXX)
+    exefile=${cfile%.c}
     cat <<CFILE > $cfile
 #include <stdio.h>
 int main (void) {
@@ -337,15 +338,15 @@ int main (void) {
   return 0;
 }
 CFILE
-    bf-gcc -bf-libdir="$destdir$installdir/lib" -bf-dragonegg="$destdir$installdir/lib/dragonegg.so" $cfile -o $exefile
-    run_with_progress byfl-test 22 $exefile
-    rm -f $cfile $exefile
+    bf-gcc -bf-libdir="$destdir$installdir/lib" -bf-dragonegg="$destdir$installdir/lib/dragonegg.so" "$cfile" -o "$exefile"
+    run_with_progress byfl-test 23 "$exefile"
+    rm -f "$cfile" "$exefile"
 
     # Say what we did.
     echo "Successfully installed LLVM, Clang, DragonEgg, and Byfl into $installdir."
     echo "It is now safe to delete $builddir."
     if [ "$gui" = yes ] ; then
-        kill $zenity_pid
+        kill "$zenity_pid"
         zenity --info --title="Finished installation" --text="Successfully installed LLVM, Clang, DragonEgg, and Byfl into $installdir.\n\nIt is now safe to delete $builddir."
     fi
 fi
