Build script passes ShellCheck

diff --git a/build-llvm-byfl b/build-llvm-byfl
--- a/build-llvm-byfl
+++ b/build-llvm-byfl
@@ -10,15 +10,15 @@
 
 # Ensure we have a version of bash that can parse the rest of this
 # file (specifically, the coproc statement).
-if [ `echo $BASH_VERSION | sed -e 's/\..*//'` -lt 4 ] ; then
+if [ "${BASH_VERSION/.*/}" -lt 4 ] ; then
     echo "${0}: This script requires bash version 4+; you're running version $BASH_VERSION" 1>&2;
     exit 1
 fi
 
 # Define a function to work around OS X's lack of "readlink -f".
 function abs_dirname() {
-  somedir=`echo "$1/" | sed 's,//*,/,g'`
-  if [ `echo "$somedir" | cut -c1` = "/" ] ; then
+  somedir=$(echo "$1/" | sed 's,//*,/,g')
+  if [ "${somedir:0:1}" = "/" ] ; then
       echo "$somedir"
   else
       mkdir -p "$somedir" > /dev/null 2>&1
@@ -101,15 +101,15 @@ if [ -z "$1" ] ; then
     exit 1
 fi
 if [ -z "$builddir" ] ; then
-    builddir=$(mktemp --directory --tmpdir=$(/bin/pwd) byfl-build.XXXXXX)
+    builddir=$(mktemp --directory --tmpdir="$(/bin/pwd)" byfl-build.XXXXXX)
 fi
-builddir=`abs_dirname "$builddir"`
-installdir=`abs_dirname "$1"`
+builddir=$(abs_dirname "$builddir")
+installdir=$(abs_dirname "$1")
 if [ -z "$numprocs" ] ; then
     # No parallel-build factor was specified -- guess a good value to use.
     if [ -e /proc/cpuinfo ] ; then
         # Linux -- get the CPU count from /proc/cpuinfo.
-        numprocs=`cat /proc/cpuinfo | egrep -c '^processor'`
+        numprocs=$(egrep -c '^processor' /proc/cpuinfo)
     else
         # OS X or other -- disable implicit parallel builds.
         numprocs=1
@@ -122,30 +122,31 @@ CXX=${CXX:-g++}
 
 # Prepare the GUI.
 if [ "$gui" = yes ] ; then
-    if [ ! `type -P stdbuf` ] ; then
+    if [ ! "$(type -P stdbuf)" ] ; then
         gui=no
-    elif [ ! `type -P zenity` ] ; then
+    elif [ ! "$(type -P zenity)" ] ; then
         gui=no
     fi
 fi
 if [ "$gui" = yes ] ; then
+    zproc_PID=""   # Prevent spurious undefined-variable warnings from ShellCheck.
     coproc zproc {
         zenity --progress --title="Byfl installation progress" --auto-kill
     }
     while [ -z "$zenity_pid" ] ; do
-        zenity_pid=`ps | awk '$NF == "zenity" {print $1}'`
+        zenity_pid=$(ps | awk '$NF == "zenity" {print $1}')
         sleep 1
     done
     function abend () {
-        test -z "$zproc_PID" || kill $zproc_PID
+        test -z "$zproc_PID" || kill "$zproc_PID"
         zenity --error --title="Fail" --text="Installation failed."
         exit 1
     }
     trap abend ERR
 else
-    zproc=(0, 1)
+    zproc=(0 1)
 fi
-exec 4>&${zproc[1]}
+exec 4>&"${zproc[1]}"
 
 # Define a function to update a progress bar during command execution
 # given a symbolic tag for the run, the expected number of lines of
@@ -159,20 +160,20 @@ function run_with_progress () {
 
     # Run the command either with or without the GUI.  Abort on error.
     logfile="$builddir/build-logs/$tag.log"
-    echo "\$ $@" > $logfile
+    echo "\$ $*" > "$logfile"
     if [ "$gui" = yes ] ; then
         # Estimate the number of lines of output we'll see.
         echo 0 1>&4
         "$@" 2>&1 | \
-            tee -a $logfile | \
-            stdbuf -oL awk '{printf "%d\n", 100*NR/MAXLN; print > "/dev/stderr"}' MAXLN=$maxlines | \
+            tee -a "$logfile" | \
+            stdbuf -oL awk '{printf "%d\n", 100*NR/MAXLN; print > "/dev/stderr"}' MAXLN="$maxlines" | \
             stdbuf -oL uniq 1>&4
         echo 100 1>&4
     else
         "$@"
     fi
     if [ "${PIPESTATUS[0]}" != 0 ] ; then
-        echo "${0}: Execution of \"$@\" failed (${PIPESTATUS[0]})" 1>&2
+        echo "${0}: Execution of \"$*\" failed (${PIPESTATUS[0]})" 1>&2
         false
         exit 1
     fi
@@ -205,22 +206,22 @@ if [ "$download" = yes ] ; then
     # Download LLVM.
     if [ "$use_llvm" = yes ] ; then
         echo "# Downloading LLVM revision $llvm_revision on $llvm_branch into $builddir" 1>&4
-        run_with_progress llvm-dl 17000 svn checkout -r $llvm_revision http://llvm.org/svn/llvm-project/llvm/$llvm_branch llvm
+        run_with_progress llvm-dl 17000 svn checkout -r "$llvm_revision" "http://llvm.org/svn/llvm-project/llvm/$llvm_branch" llvm
     fi
-    cd llvm
-    llvm_revision=`svn info | awk '/^Revision: / {print $2}'`
-    cd ..
+    pushd llvm
+    llvm_revision=$(svn info | awk '/^Revision: / {print $2}')
+    popd
 
     # Download Clang.
     if [ "$use_llvm" = yes ] ; then
         echo "# Downloading Clang revision $llvm_revision into $builddir" 1>&4
-        run_with_progress clang-dl 13000 svn checkout -r $llvm_revision http://llvm.org/svn/llvm-project/cfe/$llvm_branch llvm/tools/clang
+        run_with_progress clang-dl 13000 svn checkout -r "$llvm_revision" "http://llvm.org/svn/llvm-project/cfe/$llvm_branch" llvm/tools/clang
     fi
 
     # Download the Clang run-time system.
     if [ "$use_llvm" = yes ] ; then
         echo "# Downloading Clang RT revision $llvm_revision into $builddir" 1>&4
-        run_with_progress rts-dl 1800 svn checkout -r $llvm_revision http://llvm.org/svn/llvm-project/compiler-rt/$llvm_branch llvm/projects/compiler-rt
+        run_with_progress rts-dl 1800 svn checkout -r "$llvm_revision" "http://llvm.org/svn/llvm-project/compiler-rt/$llvm_branch" llvm/projects/compiler-rt
     fi
 
     # Download Byfl.
@@ -236,7 +237,7 @@ if [ "$download" = yes ] ; then
         echo "Downloaded a subset of LLVM, Clang, and Byfl into $builddir."
     fi
     if [ "$gui" = yes -a "$compile" = no ] ; then
-        kill $zenity_pid
+        kill "$zenity_pid"
         zenity --info --title="Finished downloading" --text="Downloaded LLVM, Clang,\nand Byfl into $builddir."
     fi
 fi
@@ -246,7 +247,7 @@ if [ "$compile" = yes ] ; then
     if [ "$use_llvm" = yes ] ; then
         # Configure LLVM and Clang.
         echo "# Configuring LLVM and Clang" 1>&4
-        cd llvm
+        pushd llvm
         if [ $configure = yes -o ! -e config.log ] ; then
             run_with_progress llvm-config 270 ./configure --prefix="$installdir" --enable-optimized --enable-debug-runtime --enable-debug-symbols --disable-assertions CC="$CC" CXX="$CXX" REQUIRES_RTTI=1
         fi
@@ -261,7 +262,7 @@ if [ "$compile" = yes ] ; then
         run_with_progress llvm-inst 810 make DESTDIR="$destdir" install
 	cp -p tools/clang/tools/scan-view/scan-view "$destdir$installdir/bin/scan-view"
 	cp -p tools/clang/tools/scan-build/scan-build "$destdir$installdir/bin/scan-build"
-        cd ..
+        popd
     fi
     export PATH="$destdir$installdir/bin:$PATH"
 
@@ -290,8 +291,8 @@ if [ "$compile" = yes ] ; then
     # Test the installation
     echo "# Testing the Byfl installation" 1>&4
     test "$gui" = yes && echo 0 1>&4
-    cfile=`mktemp --tmpdir --suffix=.c byfltest-XXXXXX`
-    exefile=`echo $cfile | sed 's/\.c$//'`
+    cfile=$(mktemp --tmpdir --suffix=.c byfltest-XXXXXX)
+    exefile=${cfile%.c}
     cat <<CFILE > $cfile
 #include <stdio.h>
 int main (void) {
@@ -299,15 +300,15 @@ int main (void) {
   return 0;
 }
 CFILE
-    bf-clang -O2 -bf-libdir="$destdir$installdir/lib" $cfile -o $exefile
-    run_with_progress byfl-test 19 $exefile
-    rm -f $cfile $exefile
+    bf-clang -O2 -bf-libdir="$destdir$installdir/lib" "$cfile" -o "$exefile"
+    run_with_progress byfl-test 19 "$exefile"
+    rm -f "$cfile" "$exefile"
 
     # Say what we did.
     echo "Successfully installed LLVM, Clang, and Byfl into $installdir."
     echo "It is now safe to delete $builddir."
     if [ "$gui" = yes ] ; then
-        kill $zenity_pid
+        kill "$zenity_pid"
         zenity --info --title="Finished installation" --text="Successfully installed LLVM, Clang, and Byfl into $installdir.\n\nIt is now safe to delete $builddir."
     fi
 fi
